# Generated by Django 5.0.3 on 2024-05-09 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pengguna', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_transfer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
                ('id_penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_penerima', to='tf.user')),
                ('id_pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_pengirim', to='tf.user')),
            ],
        ),
        migrations.CreateModel(
            name='RekeningBank',
            fields=[
                ('id_rekening', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bank', models.CharField(max_length=255)),
                ('nomor_rekening', models.CharField(max_length=255)),
                ('id_pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tf.user')),
            ],
        ),
    ]
